name: source_gen_class_visitor
version: 0.0.1
description: >
authors:
- Matthias Sokolowski <matthias.sokolowski@googlemail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'
  
dev_dependencies:
  analyzer: ^0.33.3
  build: ^1.0.0
  build_config: ^0.3.1
  source_gen: ^0.9.0
  build_runner: ^1.1.2
  test: ^1.5.1
